baseURL = "https://www.patoune-it.fr/"
title = "Patoune-IT"
theme = "PaperMod"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 6

[params]
  author = "Thomas L."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "auto"
  mainSections = ["posts"]
  displayFullLangName = true

[params.label]
  text = "Patoune-IT"
  icon = "/assets/images/patoune_logo_cat.png"
  iconHeight = 32

[params.cover]
  hiddenInList = false
  hiddenInSingle = false

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/patoune95"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/thomas-l-a365153a/"

[languages]
  [languages.fr]
    languageName = "🇫🇷 FR"
    weight = 1
    [languages.fr.params]
      description = "Blog technique"
      [languages.fr.params.homeInfoParams]
        Title = "Patoune-IT"
        Content = "Blog technique · Lead Tech · Paris, France"
    [[languages.fr.menus.main]]
      name = "Posts"
      url = "/posts/"
      weight = 1
    [[languages.fr.menus.main]]
      name = "Tags"
      url = "/tags/"
      weight = 2
    [[languages.fr.menus.main]]
      name = "Archives"
      url = "/archives/"
      weight = 3

  [languages.en]
    languageName = "🇬🇧 EN"
    weight = 2
    [languages.en.params]
      description = "Technical blog"
      [languages.en.params.homeInfoParams]
        Title = "Patoune-IT"
        Content = "Technical blog · Lead Tech · Paris, France"
    [[languages.en.menus.main]]
      name = "Posts"
      url = "/en/posts/"
      weight = 1
    [[languages.en.menus.main]]
      name = "Tags"
      url = "/en/tags/"
      weight = 2
    [[languages.en.menus.main]]
      name = "Archives"
      url = "/en/archives/"
      weight = 3
